# Welcome to Jekyll!Redcarpet
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 懂得，也要会表达
email: 
description: > # this means to ignore newlines until "baseurl:"
  我不是个伟大的程序员，我只是个有着一些优秀习惯的好程序员--by Kent Beck
url: "https://swa19.github.io/" # the base hostname & protocol for your site
github_username:  swa19

# markdown
markdown: kramdown
kramdown:
  input: GFM

include: ['/_pic']





