# Welcome to Jekyll!Redcarpet
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 每日一记
email: 
description: > # this means to ignore newlines until "baseurl:"
  做一个好开发
url: "https://swa19.github.io/" # the base hostname & protocol for your site
github_username:  swa19

# markdown
markdown: kramdown


include: ['/_pic']





